name: deploy-docker-manylinux2014_x86_64_cuda_10.2

on:
    # push:
    #     branches:
    #         - main
    release:
        types: 
            - published

jobs:
  build_docker:
        name: build
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Build and push manylinux2014_x86_64_cuda-10.2
              id: docker_build
              uses: docker/build-push-action@v5
              with:
                  push: true
                  file: ./docker/manylinux2014_x86_64_cuda_10.2/Dockerfile
                  tags: sameli/manylinux2014_x86_64_cuda_10.2:latest

            - name: Image digest
              run: echo ${{ steps.docker_build.outputs.digest }}

  test_docker:
        needs: [build_docker]
        name: test
        runs-on: ubuntu-latest
        steps:
            - name: Install Snap
              run: |
                sudo apt update
                sudo apt install snapd

            - name: Install Docker
              run: |
                sudo snap install docker
                sudo groupadd -f docker
                sudo usermod -aG docker $USER
                newgrp docker

            - name: Pull Docker Image
              run: docker pull sameli/manylinux2014_x86_64_cuda_10.2

            - name: Run Docker Image
              run: docker run -t sameli/manylinux2014_x86_64_cuda_10.2 nvcc --version
